language: r
cache: packages

env:
  global:
    - secure: "lmfPQzFEjKboufzpMLSgWJDHWS8l/N3YKX3hKJLATmmuYTCi0bVcs2ri7Zc0JgQEuBSmHMwLXall8dvbZJu7V3m0Jf0gHMOKJjEy/lNG26A9HJgrr7FanugogNA0z1il3fToRZhJHcgysB6FnU7auCjFuW/K2zRfIR/8KiacraDXKVJ/Y6af9T3mjIOgYUF6lQirNx2UxNJoMB2+2D0MMmyV/w8T/841ErxtZmfe8zfuzQ0pZcsePSc7w1+SZXuX7x1uITRJIUfEEqiN06Nic7/oz5HzsHaja8ypFTpIEsJHnJjmW7j5FwRjg5jCaZz2kZuPxVvMCECh18Rl6DjaLBlCDUnRorxHxASHYqjaOz7QipAAPhhCU7GxWO2kqK1wh56FCqaf+T9h70LY3jqDRWrR/r3v0JKBVPpGPSEZD8PFuwITtDM1AdOEwfvTrZFcuOzVxJK0pUB/0HrzLh/Rsa7Q5Baw/vekoo+kMLPsrU6KtYPV1xkX7lo0Uw0iG4fsjsWonZmWRG21pk/5hKze5toSVL00qTMc/clbtfAMMAkWQGu+eqVc0bEJIZ3bATQFFNi6YGrZAT4NF0mkznt7yc+EX5A0uk6s7jX8dGjRwHJPtgYTIbA3utxiCIcZJlQ7x54k32ru+rRo9xU9YK1g6M5kNE3bS+3mad6x6j9ty+I="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
